### ISSUE TITLE
Vundle setting 8 space tabs ?

### ISSUE THREAD

**Issue by milosgajdos83** [gmarik/Vundle.vim#530] opened 2014-10-23 09:58 UTC
I have a following minimal vim config so that I could investigate some tabbing madness in vim:

```viml
set nocompatible           " turn vi into vim
filetype off               " required by vundle
" VUNDLE SETUP
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()          " required
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
call vundle#end()            " required
filetype plugin indent on    " enable file detection

syntax on        " Always turn the syntax on
```

Looks like presence of Vundle sets 8 space indent ? Once I remove it I'm back to sanity.
It gets worse. Whatever plugin I install, it keeps the vundle's 8 space tab. I could override it globally but the I'd override indent settings of other plugins.

Am I missing something here ?

**Comment by jdevera** [comment] 2015-02-20 06:28
Inspect your 
```
:scriptnames
```
There might be something there setting this.

**Comment by jdevera** [comment] 2015-02-23 07:55
@milosgajdos83  do you still have this issue?

**Comment by jdevera** [comment] 2015-04-04 20:49
Closing, cannot reproduce. Please reopen if you have still this issue.

**Closed by jdevera** 2015-04-04 20:49 UTC
