### ISSUE TITLE
Updates go wrong when local repo is on another branch

### ISSUE THREAD

**Issue by sim590** [gmarik/Vundle.vim#593] opened 2015-04-23 04:42 UTC
Let's say I've implemented a change for a distant repository on another branch and I'm waiting for my PR to get merged. It may not be merged in the next update, and when updating local repository, I'd like to keep changes I've implemented. However, these lines happen :
```vim
let cmd_parts = [
      \ 'cd '.vundle#installer#shellesc(a:bundle.path()) ,
      \ 'git remote set-url origin ' . vundle#installer#shellesc(a:bundle.uri),
      \ 'git fetch',
      \ 'git reset --hard origin/HEAD',
      \ 'git submodule update --init --recursive',
      \ ]

```
If I was on branch `vimdoc` because I've implemented documentation for the repository, instead of `reset`'ing `master` to `origin/HEAD`, it's `reset`'ting `vimdoc`. That's a bit annoying. May be, Vundle could detect if it's not on `master` branch and prompt an `input()` and ask if update anyway?

I'm positive these lines happen because : 

```
* fb14805 (myfork/vimdoc) adding vimdoc file under ./doc/
*   c4975a4 (HEAD, origin/master, origin/HEAD, vimdoc, master) Merge pull request #184 from ciros
```

**Notice** that `vimdoc` branch is behind `myfork/vimdoc`.

**Comment by sim590** [comment] 2015-04-23 04:44
I've just thought that a more standard way would be to provide a **blacklist** array similar to how pacman handles this on Archlinux.

**Comment by av3r4ge** [comment] 2015-04-23 11:11
I haven't fully understood what happens and what you expect, but I'll give it a try.
Premise: You want to stay on a branch where you fixed something until your fix is merged and then you'll switch back to master.

When you make changes to something, you usually should do it in a new branch. So, when you edit vimdoc it should probably be a branch named something like 'fix-some-doc-issue' which starts from the branch doc.
Then, you push it to your fork, 'myfork'.
The snippet you gave from Vundle's code only runs when the origin is different from the built URL, but if your fork is named 'myfork', this is not the one that will run.
Instead, Vundle will just `git pull` which won't update the plugin, but won't mess with your changes.
When your fixes are merged, just change back to master and update.

Moreover, you can use `{'pinned': 1}` in your .vimrc in order to prevent an update of a plugin.
For example: `Plugin 'coolauthor/coolplugin', {'pinned': 1}`.

If I misunderstood you, I'm sorry. Please explain again and I'll try to answer correctly.
Though, I hope it helps.

**Comment by sim590** [comment] 2015-04-24 01:36
@av3r4ge: Yes. I think that when you're on a branch different than master and updating, the branch shouldn't change since you want to keep the changes you've made on that branch. Since this is a developper feature, it's okay to let the user merge the changes from the updated master onto his feature branch in order to stay up to date with master while staying on his feature branch. 

I didn't know about `{'pinned' : 1}` option. This can do the trick (like the blacklist I was thinking of) too, but I think that the feature I'm talking about would be a more smooth approach of updating branches without "undoing" the user branches configuration.

**Comment by av3r4ge** [comment] 2015-04-24 06:25
I'm not sure that one never wants to update a branch other than master.
Let's say I have a plugin that its development branch is "dev" and I want to follow it. I would like to switch to that branch and keep getting updates.

If you read again my second paragraph, you'll find that when you handle your repository in a certain manner, you can get your development branch done without it being touched by Vundle (you might get an error, but nothing would change).
Just for short:
* Your fork's remote name should not be origin.
* Make changes on a branch started from the branch you desire to change but with a different, more descriptive, name.

**Comment by sim590** [comment] 2015-04-24 07:47
Ok. I've done some testing and I now know what's happening thanks to the log:
```
[2015-04-24 03:24:46] 
[2015-04-24 03:24:46] Plugin gmarik/Vundle.vim
[2015-04-24 03:24:46] $ cd '/home/simon/.vim/bundle/Vundle.vim' && git pull &&
git submodule update --init --recursive
[2015-04-24 03:24:46] > Already up-to-date.
[2015-04-24 03:24:46] > 
[2015-04-24 03:24:46] Plugin URI change detected for Plugin vim-rsi
[2015-04-24 03:24:46] >  Plugin vim-rsi old URI:
https://github.com/tpope/vim-rsi.git
[2015-04-24 03:24:46] >  Plugin vim-rsi new URI:
git://github.com/tpope/vim-rsi.git
[2015-04-24 03:24:46] 
[2015-04-24 03:24:46] Plugin tpope/vim-rsi
[2015-04-24 03:24:46] $ cd '/home/simon/.vim/bundle/vim-rsi' && git remote
set-url origin 'git://github.com/tpope/vim-rsi.git' && git fetch && git reset
--hard origin/HEAD && git submodule update --init --recursive
[2015-04-24 03:24:46] > HEAD is now at dfc5288 Let CTRL-E cancel the popup menu
[2015-04-24 03:24:46] > 
[2015-04-24 03:24:46] 
[2015-04-24 03:24:46] Helptags:
[2015-04-24 03:24:46] :helptags /home/simon/.vim/bundle/Vundle.vim/doc
[2015-04-24 03:24:46] :helptags /home/simon/.vim/bundle/vim-rsi/doc
[2015-04-24 03:24:46] Helptags: 2 plugins processed
```
I have some repositories, in my `~/.vim/bundle` directory, that have the *https* uri instead of *git* uri. So, when update happens and that `HEAD` is on another branch than `master`, *this branch is reset* to `origin/HEAD` instead of `master`, **which is wrong**! It should first be sure that `HEAD` is on the `master` branch before doing `git reset --hard` or else, **it may reset the wrong branch**!

So after this I could see that my *feature branch*, which is `no_meta_opts` in this case, had been moved:
```
* 4c5af03 (myfork/no_meta_opts) documentation about disabling meta maps in insert or cmd modes
* efc6551 check if rsi_no_meta is set to 1 explicitly
* 4feb385 g:rsi_no_cmd_meta option for disabling meta in cmd mode
* 698d0a6 g:rsi_no_insert_meta option for disabling meta in insert mode
* dfc5288 (HEAD, origin/master, origin/HEAD, myfork/master, no_meta_opts, master) Let CTRL-E cancel the popup menu
* ec39927 Fix cmap <C-G>
* d57ac7d Add support for disabling meta mappings
* dd22d12 Leave the command line with CTRL-G
* f62b3ac Fix conditional
* f710ea4 Enable meta maps in normal mode
* 70889d7 Dance around load order issue
* ab46cb7 Add support for <M-BS> as delete-backward-word
* 0d07b3c Fix <M-d> in command line mode
* 14d18b3 Set ttimeout
* dd8f86f rsi.vim 1.
```
As you can see, the second time I've updated, the reset was not made because the uri was fixed the first time. Then it only did a `git pull` as you said it should:
```
[2015-04-24 03:25:36] 
[2015-04-24 03:25:36] Plugin gmarik/Vundle.vim
[2015-04-24 03:25:36] $ cd '/home/simon/.vim/bundle/Vundle.vim' && git pull &&
git submodule update --init --recursive
[2015-04-24 03:25:36] > Already up-to-date.
[2015-04-24 03:25:36] > 
[2015-04-24 03:25:36] 
[2015-04-24 03:25:36] Plugin tpope/vim-rsi
[2015-04-24 03:25:36] $ cd '/home/simon/.vim/bundle/vim-rsi' && git pull && git
submodule update --init --recursive
[2015-04-24 03:25:36] > There is no tracking information for the current branch.
[2015-04-24 03:25:36] > Please specify which branch you want to merge with.
[2015-04-24 03:25:36] > See git-pull(1) for details
[2015-04-24 03:25:36] > 
[2015-04-24 03:25:36] >     git pull <remote> <branch>
[2015-04-24 03:25:36] > 
[2015-04-24 03:25:36] > If you wish to set tracking information for this branch
you can do so with:
[2015-04-24 03:25:36] > 
[2015-04-24 03:25:36] >     git branch --set-upstream-to=<remote>/<branch>
no_meta_opts
[2015-04-24 03:25:36] > 
[2015-04-24 03:25:36] > 
[2015-04-24 03:25:37] 
[2015-04-24 03:25:37] Helptags:
[2015-04-24 03:25:37] :helptags /home/simon/.vim/bundle/Vundle.vim/doc
[2015-04-24 03:25:37] :helptags /home/simon/.vim/bundle/vim-rsi/doc
[2015-04-24 03:25:37] Helptags: 2 plugins processed
```

**Comment by jdevera** [comment] 2015-04-24 07:57
Perhaps it's worth mentioning at this point, just to clarify the assumptions of what is wrong and what is right, that Vundle *owns* all the directories under .vim/bundle.

It assumes the user is not fiddling with branches or commits and basically it will assume each clone is always in the master branch that is either up to date or behind origin/master.

The only thing you can do today to change this is to pin the plugin and then Vundle will not do any git operations in it.

For the scenario you describe, you have to pin it and handle all updates yourself. When you decide to hand it back to Vundle, if you do, the safest way to do it is to remove the repo, remove the pinned option and let Vundle make a fresh clone.

**Closed** 2015-04-24 07:57 UTC

**Comment by sim590** [comment] 2015-04-24 09:18
Well. Simply checking `git branch --no-color` for making sure branch is `master` before doing `reset` would make sense anyway:
- sturdiness of the code would be better.
- readability would be better also. You could read the code and understand that it *really* wants to reset `master` and no other branch.
Ignoring this and relying on assumptions is not the right way in my opinion.

Anyway, it appears to work *okay* if the uri is alright even if `HEAD` is not on master.

@jdevera What follows is only regarding the following quote. 

> It assumes the user is not fiddling with branches or commits

This is removing the freedom to add features yourself for your own good without getting trouble when upgrading with the program that handles the bundle directory. I think that this freedom should be one of the major strengths of handling plugins with git and Vundle. 

If you don't "mess" with the files in the bundle, you have to wait for a PR to be implemented and that is restricting the user. I don't want to depend on someone to chose if I can use a feature I've coded for a plugin, but I also want to keep track of updates while my PR is being processed.

*However, the way Vundle works for now still lets me free to do what I want. That was my opinion about what you said. I'm sure someone could have another one.*

**Comment by jdevera** [comment] 2015-04-24 09:31
> This is removing the freedom to add features yourself for your own good without getting trouble when upgrading with the program that handles the bundle directory. I think that this freedom should be one of the major strengths of handling plugins with git and Vundle.

Vundle tries to keep it simple, it has a number of assumptions to make this so. Yet it is very flexible! There is always a way to do what you want, but putting every single case in Vundle without breaking the others is not trivial. So, on this particular quote, I'll say that Vundle does not take any freedom from you, it does not prevent you from doing what you want, it will just not work well if you do thing in a way that is unexpected for Vundle. And I am not saying this will necessarily stay this way forever, I'm only saying, that the fact that you cannot do what you want to do is not unexpected and not a bug.

You do your PR, check it out in your plugin within the bundle dir, I've done that too, that's what `pinned` is for. Then keeping this up to date means fetching, rebasing, etc, a completely different workflow than just pulls to master, so Vundle cannot do that for you.

There is a very popular feature request to support locking on to a branch, tag, or commit, not yet implemented, but even if and when that is implemented, I still think you won't be able to keep your PR branch rebased with latest master through Vundle.

**Comment by sim590** [comment] 2015-04-24 20:52
> it does not prevent you from doing what you want, it will just not work well if you do thing in a way that is unexpected for Vundle. And I am not saying this will necessarily stay this way forever, I'm only saying, that the fact that you cannot do what you want to do is not unexpected and not a bug.

I understand. I was hoping we could make it so that it doesn't break in that case by a simple fix. After all, I don't know the project as well as you.

> You do your PR, check it out in your plugin within the bundle dir, I've done that too, that's what pinned is for. Then keeping this up to date means fetching, rebasing, etc, a completely different workflow than just pulls to master, so Vundle cannot do that for you.

If the URI of the local repository is the one Vundle expects, it won't reset my branch and then, I don't need pin, but I'm glad to know this option exists!

I appreciate the time you guys took to answer my questions. Thank you.

**Comment by av3r4ge** [comment] 2015-04-24 23:29
I still don't understand why you get this piece of code run if your fork is not named origin.
For example, here are my Vundle's remotes:
```
av3r4ge@archie ~/.vim/bundle/Vundle.vim (master) $ git remote -v
fork	git@github.com:av3r4ge/Vundle.vim.git (fetch)
fork	git@github.com:av3r4ge/Vundle.vim.git (push)
origin	https://github.com/gmarik/Vundle.vim.git (fetch)
origin	https://github.com/gmarik/Vundle.vim.git (push)
```
Note that origin is the URI Vundle expects and fork is my fork.
This way that reset code is never run.
I also usually name my branch differently, so no override by pull is performed. For instance, from master or whatever I `git checkout -b fix-some-bug`.
Additionally, after pushing to your fork, `git branch -u fork/fix-some-bug` should make the new branch track fork, so no errors as well. Though, I don't usually mind the errors if I know I'm on a custom branch.

**Comment by sim590** [comment] 2015-04-25 01:25
> Note that origin is the URI Vundle expects and fork is my fork.
This way that reset code is never run.

Exactly. But in my case, the uri wasn't as expected, so the `reset` occured a first time and the origin uri was fixed. Then, successive tries didn't trigger the `reset` and did only pull. If you look at the two Vundle logs I've posted, you see what happens.
