### ISSUE TITLE
BundleSearch fails, 

### ISSUE THREAD

**Issue by madiot** [gmarik/Vundle.vim#546] opened 2014-12-12 08:24 UTC
Upon `:BundleSearch` I get following error:

    message error detected in function vundle#scripts#all..<SNR>22_load_scripts..    
    <SNR>22_fetch_scripts: line 24 : Error fetching scripts!

* here is my _vimrc : 
```viml
"---------------------------
set nocompatible              " be iMproved, required
filetype off                  " required
set directory=.,$TEMP
set rtp+=~/vimfiles/bundle/Vundle.vim/
let path='~/vimfiles/bundle'
call vundle#begin(path)
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
"---------------------------
```

I did follow the guideline https://github.com/gmarik/Vundle.vim/wiki/vundle-for-windows, so i have curl/git setup

* fyi I added : 
```viml
set directory=.,$TEMP
```
because I was having error:

    E303: impossible to open file .swp for "[Vundle] search"

**Comment by jdevera** [comment] 2015-02-20 06:20
Sorry, not on a windows box here. Do you still have this problem? I've had it before due to temporary inavailability of the scripts list online.

If you still have it, can you run this and paste the output:

```viml
:echo system('curl --version')
```

**Comment by jdevera** [comment] 2015-03-18 19:27
Closing for lack of news, please feel free to reopen if you still have the issue.

**Closed by jdevera** 2015-03-18 19:27 UTC

**Comment by jhonghee** [comment] 2015-09-20 05:56
I am getting the same error.

```
Error detected while processing function vundle#scripts#all..<SNR>25_load_scripts:
line    7:
E15: Invalid expression:
E15: Invalid expression:
Error detected while processing function vundle#scripts#all:
line    5:
E712: Argument of filter() must be a List or Dictionary
line   10:
E686: Argument of reverse() must be a List
Error detected while processing function vundle#scripts#all..vundle#scripts#bundle_names:
line    1:
E712: Argument of map() must be a List or Dictionary
Error detected while processing function vundle#scripts#all..vundle#scripts#view:
line   15:
E745: Using a List as a Number
E116: Invalid arguments for function append
```

Here's my .vimrc

```
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
Plugin 'https://github.com/Shougo/neocomplete.vim.git'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Use neocomplete.
let g:neocomplete#enable_at_startup = 1

```

**Comment by nfischer** [comment] 2015-09-29 00:17
Try looking at #639 as this appears to be a duplicate

**Comment by fatso83** [comment] 2015-09-29 10:53
This is caused by a failing download of the vimscripts json file, further causing a json parsing error.

**Comment by silent-mobius** [comment] 2020-04-19 13:16
So.... how do you fix it ?

**Comment by fatso83** [comment] 2020-05-19 20:00
I am guessing the real fix would be a proper error message to the user of the actual error and then ignore it, avoiding parsing, but for now, just wait a while and hope the download works again 🤷
